using System.Threading.Tasks;
using Microsoft.UI.Xaml.Controls;

namespace DoNet.Controls;

/// <summary>
/// The DoNet lockup: a teal ring followed by the Pacifico wordmark.
/// </summary>
/// <remarks>
/// The markup (and the path data inside it) is generated by
/// <c>tools/gen_logo_control.py</c> straight from <c>Pacifico-Regular.ttf</c>.
/// The draw-on effect itself lives in <see cref="TracedWordmark"/>, which this control
/// shares with <see cref="WelcomeWordmark"/>.
/// </remarks>
public sealed partial class DoNetLogo : UserControl
{
    private readonly TracedWordmark _wordmark;
    private bool _startHidden;

    public DoNetLogo()
    {
        InitializeComponent();

        // writing order
        _wordmark = new TracedWordmark(
            [TraceD, TraceO, TraceN, TraceE, TraceT],
            [FillD, FillO, FillN, FillE, FillT],
            RingTrace);

        Unloaded += (_, _) => _wordmark.Stop();
    }

    /// <summary>
    /// Set to <c>True</c> in markup to render nothing until <see cref="PlayIntroAsync"/> runs.
    /// </summary>
    /// <remarks>
    /// Applied in the setter rather than on Loaded: XAML assigns it while the parent page is
    /// still being constructed, which is before the first frame is composed, so the logo never
    /// flashes in fully drawn.
    /// </remarks>
    public bool StartHidden
    {
        get => _startHidden;
        set
        {
            _startHidden = value;
            if (value)
            {
                _wordmark.ApplyIntroStartState();
            }
        }
    }

    /// <summary>Draws the ring, then writes the wordmark one letter at a time.</summary>
    public Task PlayIntroAsync() => _wordmark.PlayIntroAsync();

    /// <summary>Un-draws the wordmark from the last letter back to the first, then the ring.</summary>
    public Task PlayOutroAsync() => _wordmark.PlayOutroAsync();
}
