using System;
using System.Threading.Tasks;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media.Animation;
using Microsoft.UI.Xaml.Shapes;

namespace DoNet.Controls;

/// <summary>
/// The DoNet lockup: a teal ring followed by the Pacifico wordmark.
/// </summary>
/// <remarks>
/// <para>
/// The markup (and the path data inside it) is generated by
/// <c>tools/gen_logo_control.py</c> straight from <c>Pacifico-Regular.ttf</c>.
/// </para>
/// <para>
/// Each letter exists twice: a hairline "trace" Path and a solid "fill" Path sitting
/// exactly on top of it. The draw-on effect animates <see cref="Shape.StrokeDashOffset"/>
/// of the trace from "one full path length" down to zero, which slides a single dash the
/// length of the whole outline across it - the standard SVG line-draw trick. Once a
/// letter has finished tracing, its fill cross-fades in over the hairline.
/// </para>
/// <para>
/// The dash length each Path needs is already baked into its
/// <see cref="Shape.StrokeDashArray"/> by the generator (XAML measures dashes in multiples
/// of StrokeThickness, so it cannot be computed here without re-measuring the geometry).
/// Reading it back off the Path keeps the numbers in exactly one place.
/// </para>
/// </remarks>
public sealed partial class DoNetLogo : UserControl
{
    // ---- intro -------------------------------------------------------------
    private const int RingDrawMs = 620;
    private const int LetterStartMs = 250;    // delay before the first letter starts
    private const int LetterStaggerMs = 140;  // gap between consecutive letters
    private const int LetterDrawMs = 600;
    private const int FillDelayMs = 430;      // after that letter's own trace begins
    private const int FillFadeMs = 260;

    // ---- outro -------------------------------------------------------------
    private const int OutroStaggerMs = 80;
    private const int OutroFillFadeMs = 200;
    private const int OutroTraceDelayMs = 110;
    private const int OutroTraceMs = 380;
    private const int OutroRingDelayMs = 240;
    private const int OutroRingMs = 440;

    private Storyboard? _running;
    private TaskCompletionSource? _runningCompletion;
    private bool _startHidden;
    private Path[] _traces = [];
    private Path[] _fills = [];

    public DoNetLogo()
    {
        InitializeComponent();

        // writing order
        _traces = [TraceD, TraceO, TraceN, TraceE, TraceT];
        _fills = [FillD, FillO, FillN, FillE, FillT];

        Unloaded += (_, _) => Stop();
    }

    /// <summary>
    /// Set to <c>True</c> in markup to render nothing until <see cref="PlayIntroAsync"/> runs.
    /// </summary>
    /// <remarks>
    /// Applied in the setter rather than on Loaded: XAML assigns it while the parent page is
    /// still being constructed, which is before the first frame is composed, so the logo never
    /// flashes in fully drawn.
    /// </remarks>
    public bool StartHidden
    {
        get => _startHidden;
        set
        {
            _startHidden = value;
            if (value)
            {
                ApplyIntroStartState();
            }
        }
    }

    /// <summary>Letter outlines, in writing order.</summary>
    private Path[] Traces => _traces;

    /// <summary>Solid letters, in writing order.</summary>
    private Path[] Fills => _fills;

    /// <summary>Hides the fills and rewinds every trace to "not yet drawn".</summary>
    public void ApplyIntroStartState()
    {
        Stop();

        RingTrace.StrokeDashOffset = DashLength(RingTrace);

        for (var i = 0; i < Traces.Length; i++)
        {
            Traces[i].Opacity = 1;
            Traces[i].StrokeDashOffset = DashLength(Traces[i]);
            Fills[i].Opacity = 0;
        }
    }

    /// <summary>Puts the logo in its final, fully drawn state with no animation.</summary>
    public void ApplyCompleteState()
    {
        Stop();

        RingTrace.StrokeDashOffset = 0;

        for (var i = 0; i < Traces.Length; i++)
        {
            Traces[i].Opacity = 0;
            Traces[i].StrokeDashOffset = 0;
            Fills[i].Opacity = 1;
        }
    }

    /// <summary>Draws the ring, then writes the wordmark one letter at a time.</summary>
    /// <remarks>
    /// The end state is written back as local values once the storyboard finishes.
    /// A completed Storyboard only *holds* its final values; calling Stop on it - which
    /// the next animation has to do - snaps every property back to what it was before,
    /// so without this the logo would blink out between the intro and the outro.
    /// </remarks>
    public async Task PlayIntroAsync()
    {
        ApplyIntroStartState();
        await RunAsync(BuildIntro());
        ApplyCompleteState();
    }

    /// <summary>Un-draws the wordmark from the last letter back to the first, then the ring.</summary>
    public async Task PlayOutroAsync()
    {
        await RunAsync(BuildOutro());
        ApplyIntroStartState();
    }

    private Storyboard BuildIntro()
    {
        var board = new Storyboard();
        board.Children.Add(Animate(RingTrace, nameof(Shape.StrokeDashOffset),
            DashLength(RingTrace), 0, beginMs: 0, durationMs: RingDrawMs,
            ease: new CubicEase { EasingMode = EasingMode.EaseInOut }, dependent: true));

        for (var i = 0; i < Traces.Length; i++)
        {
            var begin = LetterStartMs + (i * LetterStaggerMs);

            board.Children.Add(Animate(Traces[i], nameof(Shape.StrokeDashOffset),
                DashLength(Traces[i]), 0, begin, LetterDrawMs,
                ease: new CubicEase { EasingMode = EasingMode.EaseInOut }, dependent: true));

            // the solid letter rises over its own outline, then the outline is dropped
            board.Children.Add(Animate(Fills[i], nameof(UIElement.Opacity),
                0, 1, begin + FillDelayMs, FillFadeMs));

            board.Children.Add(Animate(Traces[i], nameof(UIElement.Opacity),
                1, 0, begin + FillDelayMs + FillFadeMs, 1));
        }

        return board;
    }

    private Storyboard BuildOutro()
    {
        var board = new Storyboard();
        var count = Traces.Length;

        for (var i = 0; i < count; i++)
        {
            // reverse order: 't' lifts first, 'D' last
            var trace = Traces[count - 1 - i];
            var fill = Fills[count - 1 - i];
            var begin = i * OutroStaggerMs;
            var dash = DashLength(trace);

            // bring the hairline back so there is something to rewind
            board.Children.Add(Animate(trace, nameof(UIElement.Opacity), 0, 1, begin, 1));
            board.Children.Add(Animate(fill, nameof(UIElement.Opacity), 1, 0, begin, OutroFillFadeMs));

            // offset 0 -> +length erases from the end of the stroke backwards,
            // which reads as the pen being lifted back along the letter
            board.Children.Add(Animate(trace, nameof(Shape.StrokeDashOffset),
                0, dash, begin + OutroTraceDelayMs, OutroTraceMs,
                ease: new CubicEase { EasingMode = EasingMode.EaseIn }, dependent: true));
        }

        board.Children.Add(Animate(RingTrace, nameof(Shape.StrokeDashOffset),
            0, DashLength(RingTrace), OutroRingDelayMs, OutroRingMs,
            ease: new CubicEase { EasingMode = EasingMode.EaseIn }, dependent: true));

        return board;
    }

    private Task RunAsync(Storyboard board)
    {
        Stop();

        var completion = new TaskCompletionSource();

        _running = board;
        _runningCompletion = completion;

        board.Completed += (_, _) => completion.TrySetResult();
        board.Begin();

        return completion.Task;
    }

    private void Stop()
    {
        _running?.Stop();
        _running = null;

        // Release anyone awaiting the storyboard. Without this, stopping early - the
        // control being unloaded mid-animation, say - would leave the caller hanging
        // on a task that can never complete.
        _runningCompletion?.TrySetResult();
        _runningCompletion = null;
    }

    /// <summary>
    /// The dash length the generator baked into the Path, in StrokeThickness units -
    /// which is exactly the offset that hides the whole outline.
    /// </summary>
    private static double DashLength(Shape shape) =>
        shape.StrokeDashArray is { Count: > 0 } dashes ? dashes[0] : 0;

    private static DoubleAnimation Animate(
        DependencyObject target,
        string property,
        double from,
        double to,
        int beginMs,
        int durationMs,
        EasingFunctionBase? ease = null,
        bool dependent = false)
    {
        var animation = new DoubleAnimation
        {
            From = from,
            To = to,
            BeginTime = TimeSpan.FromMilliseconds(beginMs),
            Duration = new Duration(TimeSpan.FromMilliseconds(durationMs)),
            EasingFunction = ease,

            // StrokeDashOffset cannot be handed to the compositor, so WinUI drops the
            // animation on the floor unless it is explicitly allowed to run on the UI thread.
            EnableDependentAnimation = dependent,
        };

        Storyboard.SetTarget(animation, target);
        Storyboard.SetTargetProperty(animation, property);

        return animation;
    }
}
