using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Shapes;

namespace DoNet.Controls;

/// <summary>
/// "Welcome to DoNet" in Pacifico, written on one letter at a time.
/// </summary>
/// <remarks>
/// The markup is generated by <c>tools/gen_wordmark_control.py</c>. The draw-on effect
/// lives in <see cref="TracedWordmark"/>, shared with <see cref="DoNetLogo"/>.
/// </remarks>
public sealed partial class WelcomeWordmark : UserControl
{
    // Fourteen letters rather than the lockup's five, so the stagger is well under half
    // what the lockup uses - otherwise writing the phrase would take about three
    // seconds on its own, and this plays on every single unlock.
    private static readonly TraceTiming Timing = new()
    {
        LetterStartMs = 100,
        LetterStaggerMs = 58,
        LetterDrawMs = 520,
        FillDelayMs = 330,
        FillFadeMs = 220,

        OutroStaggerMs = 34,
        OutroFillFadeMs = 170,
        OutroTraceDelayMs = 80,
        OutroTraceMs = 300,
    };

    private readonly TracedWordmark _wordmark;
    private bool _startHidden;

    public WelcomeWordmark()
    {
        InitializeComponent();

        // Collected from the canvas rather than listed by name: the generator emits
        // fourteen of each, and document order is writing order.
        var paths = WordCanvas.Children.OfType<Path>().ToList();

        _wordmark = new TracedWordmark(
            paths.Where(p => p.Name.StartsWith("Trace", StringComparison.Ordinal)).ToList(),
            paths.Where(p => p.Name.StartsWith("Fill", StringComparison.Ordinal)).ToList(),
            ring: null,
            timing: Timing);

        Unloaded += (_, _) => _wordmark.Stop();
    }

    /// <summary>
    /// Set to <c>True</c> in markup to render nothing until <see cref="PlayIntroAsync"/> runs.
    /// </summary>
    public bool StartHidden
    {
        get => _startHidden;
        set
        {
            _startHidden = value;
            if (value)
            {
                _wordmark.ApplyIntroStartState();
            }
        }
    }

    /// <summary>Writes the phrase one letter at a time.</summary>
    public Task PlayIntroAsync() => _wordmark.PlayIntroAsync();

    /// <summary>Lifts the phrase back off, last letter first.</summary>
    public Task PlayOutroAsync() => _wordmark.PlayOutroAsync();
}
