#!/usr/bin/env python3
"""
Turns the project's icon sheet into WinUI path data.

The sheet is one Figma export with every icon sitting at absolute sheet
coordinates. tools/icons-source.json holds each icon's raw `d`, unmodified.
This script moves each one to its own origin and scales it into a 24 by 24
box, so the app can draw any of them at any size with one stroke weight.

Normalisation: the drawn shape is centred in a box sized to leave the same
one-unit margin the sheet's own 12 by 12 clip rectangles use, which is how a
10-unit shape ends up in a 12-unit box. Every icon therefore reads at the same
optical size when they sit next to each other.

Outputs:
  DoNet/Controls/LineIconData.cs   the table the app compiles against
  tools/icon-proof.png             a sheet to eyeball, when Pillow is present

Run it after changing icons-source.json. Nothing else reads the JSON.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "tools" / "icons-source.json"

TOKEN = re.compile(r"([MLHVCZ])|(-?\d*\.?\d+)")
ARITY = {"M": 2, "L": 2, "H": 1, "V": 1, "C": 6, "Z": 0}


def walk(d):
    """Yield (command, numbers), expanding the implicit repeats SVG allows."""
    toks = []
    for m in TOKEN.finditer(d):
        toks.append(m.group(1) if m.group(1) else float(m.group(2)))

    i, cmd = 0, None
    while i < len(toks):
        if isinstance(toks[i], str):
            cmd = toks[i]
            i += 1
            if cmd == "Z":
                yield "Z", []
                continue
        n = ARITY[cmd]
        yield cmd, toks[i:i + n]
        i += n
        if cmd == "M":
            cmd = "L"  # further pairs after a moveto are linetos


def points(d):
    """Every on-curve and control point, which is enough for a bounding box."""
    px = py = 0.0
    for cmd, n in walk(d):
        if cmd in ("M", "L"):
            px, py = n
            yield px, py
        elif cmd == "H":
            px = n[0]
            yield px, py
        elif cmd == "V":
            py = n[0]
            yield px, py
        elif cmd == "C":
            yield n[0], n[1]
            yield n[2], n[3]
            px, py = n[4], n[5]
            yield px, py


def flatten(d):
    """Polylines, for the proof sheet only."""
    lines, cur = [], []
    px = py = sx = sy = 0.0
    for cmd, n in walk(d):
        if cmd == "M":
            if len(cur) > 1:
                lines.append(cur)
            px, py = sx, sy = n
            cur = [(px, py)]
        elif cmd == "L":
            px, py = n
            cur.append((px, py))
        elif cmd == "H":
            px = n[0]
            cur.append((px, py))
        elif cmd == "V":
            py = n[0]
            cur.append((px, py))
        elif cmd == "C":
            x1, y1, x2, y2, x, y = n
            for k in range(1, 17):
                t = k / 16
                u = 1 - t
                cur.append((u ** 3 * px + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t ** 3 * x,
                            u ** 3 * py + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t ** 3 * y))
            px, py = x, y
        elif cmd == "Z":
            cur.append((sx, sy))
            lines.append(cur)
            cur = [(sx, sy)]
            px, py = sx, sy
    if len(cur) > 1:
        lines.append(cur)
    return lines


def normalise(d):
    """Move an icon to a local origin and scale it into a 24 by 24 box."""
    pts = list(points(d))
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    width, height = max(xs) - min(xs), max(ys) - min(ys)
    box = max(12.0, max(width, height) * 1.2)
    ox = (max(xs) + min(xs)) / 2 - box / 2
    oy = (max(ys) + min(ys)) / 2 - box / 2
    scale = 24.0 / box

    def num(v):
        return f"{round(v, 3):g}"

    out = []
    for cmd, n in walk(d):
        if cmd == "Z":
            out.append("Z")
        elif cmd == "H":
            out.append("H" + num((n[0] - ox) * scale))
        elif cmd == "V":
            out.append("V" + num((n[0] - oy) * scale))
        else:
            out.append(cmd + " ".join(
                num((v - (ox if k % 2 == 0 else oy)) * scale) for k, v in enumerate(n)))
    return " ".join(out), round(box, 2)


HEADER = '''// <auto-generated>
//     Generated by tools/build_icons.py from tools/icons-source.json.
//     Re-run the script after changing the source; do not edit this file by hand.
// </auto-generated>

namespace DoNet.Controls;

/// <summary>
/// Path data for the app's line icons, each drawn in the same 24 by 24 box.
/// </summary>
/// <remarks>
/// Every icon is normalised to one box and one stroke weight, so a single geometry
/// serves every size it is drawn at: the small mark beside a field label and the
/// larger one beside a section title are the same path scaled, not two drawings that
/// can drift apart. The sheet's own 12 by 12 clip rectangles leave a one unit margin
/// around the shape, and that ratio is what the normaliser reproduces.
/// </remarks>
internal static class LineIconData
{
'''


def main():
    source = json.loads(SOURCE.read_text())
    icons = {}
    for name, d in source.items():
        data, box = normalise(d)
        icons[name] = {"data": data, "sourceBox": box}

    names = ",\n        ".join(f'"{n}"' for n in icons)
    arms = "\n".join(f'        "{n}" => "{v["data"]}",' for n, v in icons.items())
    body = (
        HEADER
        + "    /// <summary>Every icon name, in sheet order.</summary>\n"
        + "    internal static readonly string[] Names =\n    [\n        "
        + names
        + ",\n    ];\n\n"
        + "    /// <summary>\n"
        + "    /// Path markup for <paramref name=\"kind\"/>, or null when there is no such icon.\n"
        + "    /// </summary>\n"
        + "    internal static string? For(string? kind) => kind switch\n    {\n"
        + arms
        + "\n        _ => null,\n    };\n}\n"
    )
    target = ROOT / "DoNet" / "Controls" / "LineIconData.cs"
    target.write_text(body, encoding="utf-8")
    print(f"{len(icons)} icons -> {target.relative_to(ROOT)}")
    for name, v in icons.items():
        print(f"  {name:<14} source box {v['sourceBox']:>6}")

    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        print("Pillow not installed - skipping the proof sheet")
        return 0

    cols, cell, pad, ss, size = 5, 110, 14, 6, 56
    rows = (len(icons) + cols - 1) // cols
    img = Image.new("RGB", (cols * cell * ss, rows * cell * ss), "white")
    dr = ImageDraw.Draw(img)
    for idx, v in enumerate(icons.values()):
        scale = size / 24 * ss
        offx = (idx % cols) * cell * ss + (cell * ss - size * ss) / 2
        offy = (idx // cols) * cell * ss + pad * ss
        width = max(1, int(round(2 * scale)))
        for poly in flatten(v["data"]):
            pts = [(offx + x * scale, offy + y * scale) for x, y in poly]
            if len(pts) > 1:
                dr.line(pts, fill=(43, 47, 51), width=width, joint="curve")
            for px, py in (pts[0], pts[-1]):
                r = width / 2
                dr.ellipse([px - r, py - r, px + r, py + r], fill=(43, 47, 51))
    img = img.resize((cols * cell, rows * cell), Image.LANCZOS)
    dr = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 11)
    except OSError:
        font = ImageFont.load_default()
    for idx, name in enumerate(icons):
        dr.text(((idx % cols) * cell + cell / 2, (idx // cols) * cell + cell - 16),
                name, fill=(90, 96, 102), font=font, anchor="ma")
    out = ROOT / "tools" / "icon-proof.png"
    img.save(out)
    print(f"proof sheet -> {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
