#!/usr/bin/env python3
"""
Writes DoNet/Controls/DoNetLogo.xaml from the Pacifico outlines.

The wordmark is emitted twice per letter:
  * a "trace" Path - a thin outline whose StrokeDashOffset is animated to draw it on
  * a "fill"  Path - the solid letter, faded in once its trace completes

Both share one absolutely-mapped gradient so the teal ramp runs across the whole
lockup instead of restarting inside every glyph's bounding box.

    python3 tools/gen_logo_control.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import math
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

from extract_logo_geometry import (
    EM, FONT_PATH, GAP_OVER_INK_W, HOLE_OVER_RING_D, PAD, PathPen,
    RING_D_OVER_INK_W, STROKE_W, WORD,
)

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "DoNet", "Controls", "DoNetLogo.xaml")

NAMES = {"D": "D", "o": "O", "N": "N", "e": "E", "t": "T"}  # XAML-safe element suffixes


def n(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def build():
    font = TTFont(FONT_PATH)
    scale = EM / font["head"].unitsPerEm
    cmap, glyph_set, hmtx = font.getBestCmap(), font.getGlyphSet(), font["hmtx"]

    def run(origin_x, baseline_y):
        pens, pen_x = [], origin_x
        for ch in WORD:
            g = cmap[ord(ch)]
            pen = PathPen(glyph_set, scale, baseline_y)
            glyph_set[g].draw(TransformPen(pen, (1, 0, 0, 1, pen_x / scale, 0)))
            pens.append((ch, pen))
            pen_x += hmtx[g][0] * scale
        return pens

    probe = run(0.0, 0.0)
    ink_w = max(p.maxx for _, p in probe) - min(p.minx for _, p in probe)
    ink_top = min(p.miny for _, p in probe)
    ink_bot = max(p.maxy for _, p in probe)

    ring_d = ink_w * RING_D_OVER_INK_W
    gap = ink_w * GAP_OVER_INK_W
    ring_t = (ring_d - ring_d * HOLE_OVER_RING_D) / 2
    ring_r = (ring_d - ring_t) / 2
    circ = 2 * math.pi * ring_r

    text_x = PAD + ring_d + gap - min(p.minx for _, p in probe)
    glyphs = run(text_x, PAD - ink_top)

    ring_cx = PAD + ring_d / 2
    ring_cy = PAD + (ink_bot - ink_top) / 2
    cw = max(p.maxx for _, p in glyphs) + PAD
    ch_ = max(PAD + (ink_bot - ink_top), ring_cy + ring_d / 2) + PAD

    ring_path = (f"M{n(ring_cx)},{n(ring_cy - ring_r)}"
                 f" A{n(ring_r)},{n(ring_r)} 0 1 1 {n(ring_cx)},{n(ring_cy + ring_r)}"
                 f" A{n(ring_r)},{n(ring_r)} 0 1 1 {n(ring_cx)},{n(ring_cy - ring_r)} Z")

    L = []
    a = L.append
    a('<?xml version="1.0" encoding="utf-8"?>')
    a('<!--')
    a('    DoNetLogo - the DoNet lockup (ring + Pacifico wordmark).')
    a('')
    a('    GENERATED by tools/gen_logo_control.py from Assets/Fonts/Pacifico-Regular.ttf.')
    a('    Re-run that script rather than hand-editing the path data; the dash lengths are')
    a('    arc-length measurements and will not survive manual tweaks.')
    a('')
    a('    Default state is fully drawn, so the control can be dropped onto any page as a')
    a('    static logo. Set StartHidden="True" and drive it with PlayIntroAsync/PlayOutroAsync')
    a('    to get the draw-on animation.')
    a('-->')
    a('<UserControl')
    a('    x:Class="DoNet.Controls.DoNetLogo"')
    a('    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"')
    a('    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"')
    a('    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"')
    a('    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"')
    a('    mc:Ignorable="d">')
    a('')
    a('    <UserControl.Resources>')
    a('        <!--')
    a('            MappingMode="Absolute" is load-bearing: with the default bounding-box')
    a('            mapping each letter would restart the ramp and the lockup would look')
    a('            striped instead of sharing one continuous gradient.')
    a('        -->')
    a(f'        <LinearGradientBrush x:Key="LockupBrush" MappingMode="Absolute"')
    a(f'                             StartPoint="0,0" EndPoint="{n(cw)},{n(ch_)}">')
    a('            <GradientStop Offset="0" Color="{StaticResource BrandTealDeepColor}" />')
    a('            <GradientStop Offset="1" Color="{StaticResource BrandTealSoftColor}" />')
    a('        </LinearGradientBrush>')
    a('    </UserControl.Resources>')
    a('')
    a('    <Viewbox Stretch="Uniform">')
    a(f'        <Canvas x:Name="LogoCanvas" Width="{n(cw)}" Height="{n(ch_)}">')
    a('')
    a('            <!-- Ring. The stroke IS the annulus, so sweeping the dash offset draws it. -->')
    a('            <Path x:Name="RingTrace"')
    a(f'                  Data="{ring_path}"')
    a('                  Stroke="{StaticResource LockupBrush}"')
    a(f'                  StrokeThickness="{n(ring_t)}"')
    a(f'                  StrokeDashArray="{n(circ / ring_t)},{n(circ / ring_t)}"')
    a('                  StrokeDashOffset="0"')
    a('                  StrokeDashCap="Flat" />')
    a('')
    a('            <!-- Letter outlines, traced on one after another. -->')
    for c, pen in glyphs:
        a(f'            <Path x:Name="Trace{NAMES[c]}" Opacity="0"')
        a(f'                  Data="{" ".join(pen.commands)}"')
        a('                  Stroke="{StaticResource LockupBrush}"')
        a(f'                  StrokeThickness="{STROKE_W}"')
        a(f'                  StrokeDashArray="{n(pen.length / STROKE_W)},{n(pen.length / STROKE_W)}"')
        a('                  StrokeDashOffset="0"')
        a('                  StrokeLineJoin="Round" StrokeDashCap="Round"')
        a('                  StrokeStartLineCap="Round" StrokeEndLineCap="Round" />')
    a('')
    a('            <!-- Solid letters, cross-faded in over their own trace. -->')
    for c, pen in glyphs:
        a(f'            <Path x:Name="Fill{NAMES[c]}"')
        a(f'                  Data="F1 {" ".join(pen.commands)}"')
        a('                  Fill="{StaticResource LockupBrush}" />')
    a('')
    a('        </Canvas>')
    a('    </Viewbox>')
    a('</UserControl>')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(os.path.abspath(OUT), "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")

    print(f"wrote {os.path.abspath(OUT)}")
    print(f"  canvas {n(cw)} x {n(ch_)}   ring d={n(ring_d)} t={n(ring_t)}  dash={n(circ / ring_t)}")
    for c, pen in glyphs:
        print(f"  {c}: dash {n(pen.length / STROKE_W)}")


if __name__ == "__main__":
    build()
