#!/usr/bin/env python3
"""
Writes DoNet/Controls/WelcomeWordmark.xaml from Pacifico-Regular.ttf.

Same trick as tools/gen_logo_control.py, minus the ring: every letter is emitted
twice - a hairline "trace" Path whose StrokeDashOffset is animated to draw it on, and
a solid "fill" Path that cross-fades in once the trace completes.

Letters are named by index rather than by character, because "Welcome to DoNet" repeats
'o' and 'e' and XAML names have to be unique.

    python3 tools/gen_wordmark_control.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

from extract_logo_geometry import EM, FONT_PATH, PAD, PathPen

WORD = "Welcome to DoNet"

# Thicker than the 2.2 the lockup uses. This wordmark is roughly three times wider, so
# it renders at a smaller scale for the same on-screen width; without the bump the
# traced line would come out noticeably finer than the splash screen's.
STROKE_W = 3.0

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "DoNet", "Controls", "WelcomeWordmark.xaml")


def n(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def build():
    font = TTFont(FONT_PATH)
    scale = EM / font["head"].unitsPerEm
    cmap, glyph_set, hmtx = font.getBestCmap(), font.getGlyphSet(), font["hmtx"]

    def run(origin_x, baseline_y):
        """Draw the word once; returns (char, pen) for every glyph that has ink."""
        pens, pen_x = [], origin_x
        for ch in WORD:
            name = cmap[ord(ch)]
            if ch != " ":
                pen = PathPen(glyph_set, scale, baseline_y)
                glyph_set[name].draw(TransformPen(pen, (1, 0, 0, 1, pen_x / scale, 0)))
                pens.append((ch, pen))
            pen_x += hmtx[name][0] * scale
        return pens

    # pass 1: find the true ink box with the baseline at y = 0
    probe = run(0.0, 0.0)
    ink_left = min(p.minx for _, p in probe)
    ink_top = min(p.miny for _, p in probe)
    ink_bot = max(p.maxy for _, p in probe)

    # pass 2: shift the whole run so the ink sits at PAD,PAD
    glyphs = run(PAD - ink_left, PAD - ink_top)

    cw = max(p.maxx for _, p in glyphs) + PAD
    ch_ = PAD + (ink_bot - ink_top) + PAD

    L = []
    a = L.append
    a('<?xml version="1.0" encoding="utf-8"?>')
    a('<!--')
    a('    WelcomeWordmark - "Welcome to DoNet" in Pacifico, no ring.')
    a('')
    a('    GENERATED by tools/gen_wordmark_control.py from Assets/Fonts/Pacifico-Regular.ttf.')
    a('    Re-run that script rather than hand-editing the path data; the dash lengths are')
    a('    arc-length measurements and will not survive manual tweaks.')
    a('')
    a('    Letters are indexed, not named after their character, because the phrase repeats')
    a('    o and e and XAML names must be unique.')
    a('-->')
    a('<UserControl')
    a('    x:Class="DoNet.Controls.WelcomeWordmark"')
    a('    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"')
    a('    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"')
    a('    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"')
    a('    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"')
    a('    mc:Ignorable="d">')
    a('')
    a('    <UserControl.Resources>')
    a('        <!--')
    a('            MappingMode="Absolute" is load-bearing: with the default bounding-box')
    a('            mapping each letter would restart the ramp and the phrase would look')
    a('            striped instead of sharing one continuous gradient.')
    a('        -->')
    a('        <LinearGradientBrush x:Key="WordmarkBrush" MappingMode="Absolute"')
    a(f'                             StartPoint="0,0" EndPoint="{n(cw)},{n(ch_)}">')
    a('            <GradientStop Offset="0" Color="{StaticResource BrandTealDeepColor}" />')
    a('            <GradientStop Offset="1" Color="{StaticResource BrandTealSoftColor}" />')
    a('        </LinearGradientBrush>')
    a('    </UserControl.Resources>')
    a('')
    a('    <Viewbox Stretch="Uniform">')
    a(f'        <Canvas x:Name="WordCanvas" Width="{n(cw)}" Height="{n(ch_)}">')
    a('')
    a('            <!-- Letter outlines, traced on one after another. -->')
    for i, (c, pen) in enumerate(glyphs):
        a(f'            <!-- {c} -->')
        a(f'            <Path x:Name="Trace{i:02d}" Opacity="0"')
        a(f'                  Data="{" ".join(pen.commands)}"')
        a('                  Stroke="{StaticResource WordmarkBrush}"')
        a(f'                  StrokeThickness="{STROKE_W}"')
        a(f'                  StrokeDashArray="{n(pen.length / STROKE_W)},{n(pen.length / STROKE_W)}"')
        a('                  StrokeDashOffset="0"')
        a('                  StrokeLineJoin="Round" StrokeDashCap="Round"')
        a('                  StrokeStartLineCap="Round" StrokeEndLineCap="Round" />')
    a('')
    a('            <!-- Solid letters, cross-faded in over their own trace. -->')
    for i, (c, pen) in enumerate(glyphs):
        a(f'            <Path x:Name="Fill{i:02d}"')
        a(f'                  Data="F1 {" ".join(pen.commands)}"')
        a('                  Fill="{StaticResource WordmarkBrush}" />')
    a('')
    a('        </Canvas>')
    a('    </Viewbox>')
    a('</UserControl>')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(os.path.abspath(OUT), "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")

    print(f"wrote {os.path.abspath(OUT)}")
    print(f"  canvas {n(cw)} x {n(ch_)}   aspect {cw / ch_:.3f}   {len(glyphs)} glyphs")
    print(f"  dash lengths: {', '.join(n(p.length / STROKE_W) for _, p in glyphs)}")


if __name__ == "__main__":
    build()
